### DISCUSSION TITLE
English caracters

### DISCUSSION THREAD

**Discussion by Sekai1942** [Trunks1982/Daikin-Rotex-HPSU-CAN#75] [General]
Hi. i install the rotex canbus serial monitor on my esphome but the language is in german.
Can you please make one in english, or tell what to change so that i get english words.
Thanks

**Comment by wrfz** [comment]
How did you flash your ESP? The language can only be changed if you flash a yaml.
You can set the language in the yaml as follows:

```
daikin_rotex_can:
  id: rotext_hpsu
  language: en
  ...
```
