### DISCUSSION TITLE
Aufbau CAN + X10A Serielle Schnittstelle

### DISCUSSION THREAD

**Discussion by Jogiarea** [Trunks1982/Daikin-Rotex-HPSU-CAN#96] [General]
Hi, mega cooles Projekt, das macht die Rotex mal so richtig smart.

Aktuell (schon ein paar Jahre) nutze ich das ESP Altherma Projekt von raomin
[](https://github.com/raomin/ESPAltherma)

Angeschlossen mit nem ESP32 NodeMCU direkt an die X10A (serielle Schnittstelle)

Leider lassen sich hier mit dem ESPAltherma Projekt nur daten auslesen.

Daher wäre mir diese Lösung hier am liebsten.

Unter dem Link zur seriellen Schnittstelle zu wrfz sehe ich aktuell auch nur das Auslesen der Daten, Steuern aber nicht.

Kann ich bei diesem Projekt die serielle Schnittstelle (X10A) auch verwenden, um zu steuern oder geht das nur über die CanL/H Signalschnittstelle?

Ich vermute mal nicht, da die serielle Schnittstelle auf uart und nicht auf Can läuft, bin hier aber leider nicht vom Fach, daher die Rückfrage

Was aber gehen sollte ist die 3,3v von der X10A Schnittstelle abzuziehen, oder?

**Comment by wrfz** [comment]
> Unter dem Link zur seriellen Schnittstelle zu wrfz sehe ich aktuell auch nur das Auslesen der Daten, Steuern aber nicht.


### 📦 Überblick über drei zusammenhängende Projekte

Bitte wirf einen Blick auf diese drei GitHub-Projekte – sie arbeiten nahtlos zusammen:

[Daikin-Rotex-HPSU-CAN-Seriell](https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN-Seriell)
    → Das CAN-Projekt zur Steuerung deiner HPSU/Altherma-Anlage und zum Auslesen der Wasserkreisdaten.

[esphome-components](https://github.com/wrfz/esphome-components)
    → Ergänzendes serielles Projekt zum Auslesen der Kältekreisdaten (ähnlich wie ESPAltherma, jedoch auf ESPhome-Basis).

[daikin-rotex-hpsu-dashboard](https://github.com/wrfz/daikin-rotex-hpsu-dashboard)
    → Ein Home Assistant Dashboard für eine anschauliche Live-Übersicht aller relevanten Werte – hilfreich zum Verständnis der Anlage.

Alle drei Projekte sind in den jeweiligen Readmes miteinander verlinkt.
➡️ Empfehlung: Lies alle Readmes gründlich durch – das klärt viele Fragen von selbst.

Tipp: Das CAN- und das serielle Projekt lassen sich entweder gemeinsam auf einem einzigen ESP oder auf zwei separaten ESPs betreiben.

<br>
<br>
<br>

> Was aber gehen sollte ist die 3,3v von der X10A Schnittstelle abzuziehen, oder?

### ⚠️ Spannungsversorgung über die X10A-Schnittstelle

- X10A liefert 5V, nicht 3,3V – das ist entscheidend!

- Ich verwende zwei ATOM S3 Lite und ein ATOM CAN-Modul (5 V-kompatibel) – das kann ich sehr empfehlen.

- Wichtig: Die meisten klassischen ESP32-Boards (wie das ESP32-S3-WROOM) arbeiten intern mit 3,3 V und sind nicht 5V-tolerant an den Datenpins.

   - Auch wenn einige Boards gelegentlich 5V an VCC zu verkraften scheinen: Die GPIOs sind offiziell nur für 3,3 V spezifiziert.

- Falls du also 5V von der X10A-Schnittstelle abgreifen willst, achte auf passende Pegelwandler oder verwende ESP-Boards mit integrierter 5V-Toleranz wie die ATOMs.

**Reply by Jogiarea** [reply]
Danke für deine ausführliche Antwort, hab die Readmes beide gelesen, war mir hier nur nicht sicher, ob ich das richtig verstehe

Werde mal die Teile ordern und dann mal testen, 
Wenns es Funktioniert gebe ich hier eine Rückmeldung inkl. Fotos vom Aufbau, kann aber etwas dauern

**Comment by wrfz** [comment]
@Jogiarea Fragen sind sehr willkommen! Allerdings bitte in Zukunft unter [Discussion](https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN-Seriell/discussions). `Issues` sind nur für Fehler da.

**Reply by Jogiarea** [reply]
Sorry dafür hab ich falsch geklickt

**Comment by Jogiarea** [comment]
Hallo,

Habe das Thema mal Umbenannt.
Habe mir einen ESP32 S3 DevKit WROOM geordert und den CAN Adapter.
[Pinout ESP32 S3 DevKit](https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2024/09/ESP32-S3-pinout.jpg?quality=100&strip=all&ssl=1)

Hier mal der Aufriss, wie ich es anschließen würde, hier bin ich nicht sicher, ob ich die passenden Pins für RX/TX ausgewählt und zugeordnet habe.
![Anschluss ESP32-S3-DevKitC-1 Rotex_Daikin HPSU_Altherma](https://github.com/user-attachments/assets/06d667e6-4255-4c1c-8ce2-d9a2209575d1)


Hier der angepasste Code:
Bin mir nicht sicher ob das so funktioniert und die external Componetnts so akzeptiert werden


```yaml
esphome:
    name: hpsu-can-uart
    friendly_name: HPSU.CAN.UART
    platformio_options:
        build_unflags:
            - "-std=gnu++11"
            - "-fno-rtti"
        build_flags:
            - "-std=gnu++17"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

external_components:
  - source: github://Trunks1982/Daikin-Rotex-HPSU-CAN
  - source: github://wrfz/esphome-components
    components: [daikin_rotex_uart]
    refresh: 0s   

#
#external_components:   # Use this block instead of the one above if you want to use the development branch
#  - source:
#      type: git
#      url: https://github.com/Trunks1982/Daikin-Rotex-HPSU-CAN.git
#      ref: dev
#    refresh: 0s

logger:
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  version: 3

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none

  ap:
    ssid: DaikinRotex Fallback Hotspot
    password: H3jGqANSa7aL

captive_portal:

time:
  - platform: homeassistant

debug:
  update_interval: 5s

sensor:
  - platform: uptime
    type: seconds
    name: Uptime Seconds
  - platform: uptime
    type: timestamp
    name: Uptime Timestamp
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s

button:
  - platform: restart
    name: "Rotex ESP Restart"
#switch:
#  - platform: gpio
#    name: Smart Grid
#    pin:
#      number: GPIO06
#      inverted: true

#  - platform: gpio
#    name: EVU
#    pin:
#      number: GPIO05
#      inverted: true

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID

canbus:
  - platform: esp32_can
    id: can_bus
    can_id: 0x680
    tx_pin: GPIO43
    rx_pin: GPIO44
    bit_rate: 20kbps

daikin_rotex_can:
  id: rotext_hpsu
  language: de
  canbus_id: can_bus
  update_interval: 30

  # Manche Tv-, TvBH- oder Tr-Sensoren liefern Werte mit Abweichungen.
  # Über ein Offset kann diese Abweichung korrigiert werden, um die Fehlererkennung defekter 3-Wegeventile zu präzisieren.
  # Zeigt der Tv-Sensor beispielsweise eine um 1,5 °C zu hohe Temperatur, sollte das Tv-Offset auf -1,5 gesetzt werden.
  # Liefert er dagegen um 1,2 °C zu geringe Werte, ist das Offset auf 1,2 zu setzen.
  # Das Gleiche gilt für TvBH und Tr.
  #tv_offset: -1.0
  #tvbh_offset: -1.0
  #tr_offset: -1.0

  #max_spread_tvbh_tv: 0.5  # Legt Tv-TVBH-Schwellwert fest, bei dem die DHW-Ventil-Fehler-Erkennung auslösen soll
  #max_spread_tvbh_tr: 0.5  # Legt TVBH-Tr-Schwellwert fest, bei dem die BPV-Ventil-Fehler-Erkennung auslösen soll

  log_filter:
    name: Log Filter
  custom_request:
    name: Custom Request
  dump:
    name: Dump Senors
  project_git_hash:
    name: Project Git Hash
  entities:

# Info

    error_code:
      name: Fehlercode

    mode_of_operating:
      name: Betriebsart
    ext:
      name: Ext
# RT
    circulation_pump:
      name: Umwaelzpumpe
# EHS
    bypass_valve:
      name: BPV
    tv:
      name: Heizkreis Vorlauf (TV)
      update_interval: 5
    tvbh:
      name: Vorlauftemperatur Heizung (TVBH)
      update_interval: 5
    tr:
      name: Ruecklauftemperatur Heizung
      update_interval: 5
    tdhw1:
      name: Warmwassertemperatur
    tdhw2:
      name: Warmwassertemperatur 2
    temperature_outside:  # ta
      name: Aussentemperatur
# V
# TVBH2
# TR2
# Tdhw2
    tliq:
      name: Tliq
    ta2:
      name: TA2
# quiet

# Übersicht
    water_pressure:
      name: Wasserdruck
    t_hs:
      name: T-WE
# T-WE Soll
    t_ext:  # Oder gehört hier temperature_outside rein?
      name: T-Aussen
# T-WW
# T-WW Soll
# T-Rücklauf
    flow_rate:
      name: Durchfluss
      update_interval: 10
# T-HK
# T-HK Soll
    status_kesselpumpe:
      name: Status Kesselpumpe
    status_kompressor:
      name: Status Kompressor
    runtime_compressor:
      name: Laufzeit Compressor
    runtime_pump:
      name: Laufzeit Pump
    dhw_mixer_position:
      name: DHW Mischer Position
    qboh:
      name: EHS für DHW
    ehs_for_ch:
      name: EHS fuer CH
    energy_cooling:
      name: Energie Kühlung
    qch:
      name: Energie Heizung
    total_energy_produced:
      name: Erzeugte Energie Gesamt
    qdhw:
      name: Energie für WW
    total_electrical_energy:
      name: Elektrische Energie Gesamt
#WE Typ
#SwNr B1/U1
#SwNr Regler
#SwNr RTXRT

# ESP custom sensors
    energy_saving_mode:
      name: ES mode

# Betriebsart
    operating_mode:
      name: Betriebsmodus
      update_interval: 5

# Raum Soll Tag
    target_room1_temperature:
      name: Raumsoll 1
      type: select
# T-RaumSoll 2
# T-RaumSoll 3

# Raum Soll Nacht
  # T-Absenkung
  # T-Abwesend

# WW Solltemp
    target_hot_water_temperature:
      name: T-WW-Soll1
      type: select

# T-WWSoll 2
# T-WWSoll 3

# WW Install
    dhw_run:
      name: Warmwasser bereiten
    1_dhw:
      name: 1 x Warmwasser
    hp_hyst_tdhw:
      name: WPHyst TDHW
    delay_time_for_backup_heating:
      name: Wartezeit BOH

# Konfiguration

# Konfiguration -> Installation
# Sprache
# Datum
    #system_date_day:
    #  name: System Date Day
    #  internal: true
    #system_date_month:
    #  name: System Date Month
    #  internal: true
    #system_date_year:
    #  name: System Date Year
    #  internal: true
    #system_date:
    #  name: System Date
# Uhrzeit
    #system_time_hour:
    #  name: System Time Hour
    #  internal: true
    #system_time_minute:
    #  name: System Time Minute
    #  internal: true
    #system_time_second:
    #  name: System Time Second
    #  internal: true
    #  update_interval: 1
    #system_time:         # Diese Entity lässt HA - DB schnell anwachsen! Bitte in HA->recorder->exclude->entities eintragen!
    #  name: System Time

#...
    outdoor_unit:
      name: Aussengerät
    indoor_unit:
      name: Innengerät
    function_ehs:
      name: Funktion EHS
    ch_support:
      name: HZ Unterstützung
    bivalence_function:
      name: Bivalenzfunktion
    smart_grid:
      name: Smart Grid
    sg_mode:
      name: SG Modus
# HT/NT Funktion
# HT/NT Anschluss
# Raumthermostat
# Interlinkfunktion
# Konfig MFR 1
# Entlüftungsfunktion
# PWM Konfig
    circulation_pump_min:
      name: Umwälzpumpe Min
    circulation_pump_max:
      name: Umwälzpumpe Max
# ...
# Sensor Konfig
    external_temp_sensor:
      name: SKonfig T-Außen
    # SKonfig T-WW
    # SKonfig Druck
# AF Anspassung
# Terminal Adresse
# Konfig System

# Konfiguration -> Anlagenkonfiguration

    power_dhw:
      name: Leistung WW
      #type: select
    power_ehs_1:
      name: Leistung EHS Stufe 1
    power_ehs_2:
      name: Leistung EHS Stufe 2
    power_biv:
      name: Leistung BIV
    tdiff_dhw_ch:
      name: TDiff-WW HZU
    max_heating_temperature:
      name: Max Temp Heizung
    bivalence_temperature:
      name: Bivalenztemperatur
    quiet:
      name: Flüsterbetrieb
#Sonderfunkt Schaltk
#Wartezeit Sonderfunkt
    t_dhw_1_min:
      name: Schaltschwelle TDHW
    delta_temp_ch:
      name: Spreizung HZ
    delta_temp_dhw:           # service
      name: Spreizung WW
#VerzZeitPumpe                # service
    flow_rate_min:            # service
      name: Durchfluss Min
    flow_rate_setpoint:       # service
      name: Durchfluss Soll
    flow_rate_calc:           # service
      name: DurchflussBer
    flow_rate_hyst:           # service
      name: Durchfluss Hyst
    supply_temperature_adjustment_heating:
      name: Anpassung T-VL Heizen
    supply_temperature_adjustment_cooling:
      name: Anpassung T-VL Kühlen
    min_pressure:
      name: Min Druck
    max_pressure:
      name: Max Druck
    set_pressure:
      name: Soll Druck
    max_pressure_drop:
      name: Max Druckverlust
#Relaistest

# Konfiguration -> HZK Konfig
    hk_function:
      name: HK Funktion
    temperature_antifreeze:
      name: T-Frostschutz
    building_insulation:
      name: Gebäudedämmung
#Estrich
#Estrichprogramm

# Konfiguration -> HZK Konfig -> Heizen

    heating_limit_day:
      name: Heizgrenze Tag
    heating_limit_night:
      name: Heizgrenze Nacht
    heating_curve:
      name: Heizkurve
#Raumeinfluss
#RF Anpassung
    flow_temperature_day:
      name: T Vorlauf Tag
    flow_temperature_night:
      name: T Vorlauf Nacht
    max_target_flow_temp:
      name: Max T-Vorlauf
    min_target_flow_temp:
      name: Min T-Vorlauf
    heating_curve_adaptation:
      name: Heizkurvenadaption

# Konfiguration -> HZK Konfig -> Kühlen

#StartKühlen A-Temp
#MaxKühlen A-Temp
#VL-SollStartKühlen
#VL-SollMaxKühlen
#MinVL-SollKühlen
#T-VLKühlen
#T_H/K Umschaltung
#KühlsollwertKorr

#Konfiguration -> WW Konfig

    circulation_with_dhw_program:
      name: Zirk mit WW-Prog
    circulation_interval_on:
      name: ZirkInterval An
    circulation_interval_off:
      name: ZirkInterval Aus
    antileg_day:
      name: AntilegTag
#AntilegZeit
    antileg_temp:
      name: AntilegTemp
    max_dhw_loading:
      name: Max WW Ladezeit
    dhw_off_time:
      name: WW Sperrzeit

# Others

    electric_heater:
      name: Heizstäbe - Für Pumpen nach Oktober 2018
    thermal_power:
      name: Thermische Leistung
    optimized_defrosting:
      name: Abtau-Optimierung
    temperature_spread:
      name: Spreizung
    tv_tvbh_delta:
      name: Tv-TVBH Delta
    tvbh_tr_delta:
      name: TVBH-Tr Delta
    vorlauf_soll_tv_delta:
      name: VorlaufSoll-Tv Delta

# Rocon U1

    #t_room:
    #  name: Raum-Ist

# To be categorized

    target_supply_temperature:
      name: Vorlauf Soll
    supply_setpoint_regulated:
      name: Vorlauf Soll Geregelt
	  
	  
	  
	  
uart:
  id: uart_bus
  tx_pin: GPIO17
  rx_pin: GPIO18
  baud_rate: 9600
  parity: EVEN
  data_bits: 8
  stop_bits: 1

daikin_rotex_uart:
  id: rotext_hpsu_uart
  uart_id: uart_bus
  language: de
  #outdoor_unit: RRLQ006CAV3  #Please comment in your outdoor unit
  #outdoor_unit: RRLQ008CAV3
  #outdoor_unit: RRLQ011CAW1
  #outdoor_unit: ERLQ016CAW1
  #outdoor_unit: ERGA06EAV3
  #outdoor_unit: ERGA08DAV3
  #outdoor_unit: RRGA08DAV3
  project_git_hash:
    name: Project Git Hash
  entities:
    mode_of_operating:
      name: Betriebsart (UART)
    t_liq:
      name: Temperatur Flüssigkeitsleitung
    liq_pressure:
      name: Kältemitteldruck
    t_liq2:
      name: Kältemitteltemperatur
    exv:
      name: Expansionsventil
    exch_temp:
      name: Temperatur Lamellenwärmetauscher
    fan_speed:
      name: Ventilatordrehzahl
    temp_after_compr:
      name: Temperatur nach Kältemittelverdichter
    inv_freq:
      name: Kompressor Drehzahl
    inv_prim_current:
      name: INV Primary Current
    inv_sec_current:
      name: INV Secondary Current
    dhw_temp:
      name: DHW tank temp
    tv:
      name: Vorlauftemeratur (TV)
    tv_bh:
      name: Vorlauftemeratur (TVBH)
    tr:
      name: Rücklauftemperatur
    outdoor_temp:
      name: Outdoor Air Temp
    tgt_cond_temp:
      name: Zielverflüssigungstemperatur
    buh1:
      name: Heizstab Stufe 1
    buh2:
      name: Heizstab Stufe 2
    buh_bsh:
      name: Heizstab Speicher
    press_eq:
      name: Druckausgleich
    4_way_valve:
      name: 4-Wege-Ventil
    defrost_operation:
      name: Abtauvorgang
    #voltage:  # Currently only known to be supported by ECH2O
    #  name: Spannung
```



Würde das so (WLAN und Passwörter noch ausgefüllt) flashen und aufbauen.

Falls was auffallen sollte gerne melden
